# Generated by Django 2.0 on 2018-09-03 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=50)),
                ('crn', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='A little description can be very helpful for others!')),
                ('document', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_courses', to='files.CoursesNames')),
            ],
        ),
    ]
