# Generated by Django 2.0 on 2018-08-29 21:46

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(choices=[('data structure', 'data structure'), ('software enginering', 'software enginering '), ('discrete structure ', 'discrete structure'), ('web dev', 'web dev')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='A little description can be very helpful for others!')),
                ('document', models.FileField(upload_to=files.models.Document.content_file_name)),
                ('uploaded_at', models.DateTimeField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_courses', to='files.CoursesNames')),
            ],
        ),
    ]
