# Generated by Django 2.0 on 2018-09-03 20:59

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=files.models.Document.content_file_name),
        ),
    ]
