# Generated by Django 2.0 on 2018-09-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesnames',
            name='crn',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursesnames',
            name='courses',
            field=models.CharField(max_length=50),
        ),
    ]
