# Generated by Django 2.0 on 2018-09-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20180903_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesnames',
            name='crn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
