# Generated by Django 2.0 on 2018-09-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20180904_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(help_text='A little description can not be harmful!'),
        ),
    ]
